service: serverless-api
provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
plugins:
- serverless-webpack
custom:
  webpack: ./build/webpack.config.js
  webpackIncludeModules: true
functions:
  hello:
    handler: index.hello
    events:
    - http:
        path: hello
        method: get